name: Build Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask reportlab requests pypdf pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller -F --add-data templates:templates app.py

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: app-executable
        path: dist\app.exe 
